### ISSUE TITLE
【Bug】文件树侧栏无法拖动，且点击失灵

### ISSUE THREAD

**Issue by Moyf** [XuQuan-nikkkki/FolderFile-Splitter-Plugin#33]
如视频：https://github.com/user-attachments/assets/29f743d9-3ce4-42f1-b447-fa850f69e60f

印象里以前这个中间的分隔线是可以拖动的……是我记错了吗？
另外现在点击文件名的时候，时灵时不灵的，失灵的时候既没办法展开文件夹，又没办法打开对应文件夹。

我的设置如下：
![Image](https://github.com/user-attachments/assets/76f96868-4c0b-4020-9eed-043d102fc55d)

版本是最新的 Release，但是正如 #29 所说，manifest 文件中的版本号还是 `0.2.3`，所以不确定实际的版本是否是最新。

**Comment by XuQuan-nikkkki** [comment]
中间的分割线是可以拖动的，但视频里我没看到分割线，因为现在没设置两列的最小宽度，所以可能是因为左边太窄了，得先把左边拉宽一点。

点击文件夹因为你现在是选的点击切换图标来展开文件夹，所以点文件名没用，可以换成文件名试试。因为这次适配主题，所以把切换图标的位置挪到外层了，所以以前可能点击图标就可以展开+选中，现在就只负责展开了，之后我再来优化一下。

版本号我再看看

**Comment by Moyf** [comment]
> 中间的分割线是可以拖动的，但视频里我没看到分割线，因为现在没设置两列的最小宽度，所以可能是因为左边太窄了，得先把左边拉宽一点。
> 
> 点击文件夹因为你现在是选的点击切换图标来展开文件夹，所以点文件名没用，可以换成文件名试试。因为这次适配主题，所以把切换图标的位置挪到外层了，所以以前可能点击图标就可以展开+选中，现在就只负责展开了，之后我再来优化一下。
> 
> 版本号我再看看

嗯……那也有可能是我的某个 CSS 把它给搞不见了，我再调查看看。
（顺便问下之前的 #5 里提到的“展开/收缩”文件树功能会做吗）

另外我感觉固定宽度（现在似乎是写死的 `140px`？）有点不太够，很多内容都显示不下：
![Image](https://github.com/user-attachments/assets/19590048-240b-451b-9eb2-dde79e116c61)

我自己加了个 CSS 做成自适应的宽度：
```css
/* 左边的侧栏 */
.ffs__layout-pane.ffs__folders-pane--horizontal {
    width: auto !important;
    max-width: max(30%, 200px) !important;
}
```

> 另外，我这边安装了不少 CSS Snippets，所以如果样式和你那边不一致大概率是 CSS 导致的错误，那种情况下无视就好 `_(:з」∠)_`
